# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            LSU LaTeX
tagline:          Presentations
description:      'Beamer theme and Powerdot style using LSU&#39;s colors'
url:              http://www.alexpacheco.net/
baseurl:          LSUBeamer/

author:
  name:           'Alex Pacheco'
  url:            http://www.alexpacheco.net

#paginate:         

# Custom vars
version:          1.2

github:
  repo:           https://github.com/alexpacheco/LSUBeamer
  home:           https://github.com/alexpacheco
