# Dependencies
markdown:redcarpet
highlighter:pygments

# Permalinks
permalink:pretty
relative_permalinks:true

# Setup
title:LSU
tagline:LaTeX Presentations
description:Beamer Theme and Powerdot style file using LSU&#39;s purple and gold color scheme
url:http://www.alexpacheco.us/LSUBeamer/
baseurl:

author:
  name:Alex Pacheco
  url:http://www.alexpacheco.us

paginate:

# Custom vars
version:1.2

github:
repo:https://github.com/alexpacheco/LSUBeamer
