# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ''
tagline:          'Beamer Themes for LaTeX Presentations'
description:      ''
url:              http://www.alexpacheco.us/LSUBeamer/
baseurl:          

author:
  name:           'Alex Pacheco'
  url:            http://www.alexpacheco.us

paginate:         

# Custom vars
#version:          1.2

github:
  repo:           https://github.com/alexpacheco/LSUBeamer
