# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            LSU LaTeX
tagline:          Presentations
description:      'Beamer theme and Powerdot style using LSU&#39;s colors'
url:              http://www.alexpacheco.us/LSUBeamer
baseurl:          /

author:
  name:           'Alex Pacheco'
  url:            http://www.alexpacheco.us

#paginate:         

# Custom vars
version:          1.2

github:
  repo:           https://github.com/alexpacheco/LSUBeamer
  home:           https://github.com/alexpacheco
